version: '3'
services:

    laravel-base-web:
        container_name: myits-softwarehub
        image: dptsi/laravel-web-dev
        volumes:
            - ./src:/var/www/html
        environment: 
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${VIRTUAL_PORT}
            - SELF_SIGNED_HOST=${SELF_SIGNED_HOST}
        dns:
            - 202.46.129.2
            - 202.46.129.3
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - nginx-proxy-network

networks:
    nginx-proxy-network:
        external: true